name: DistanceLeveledMonsters
version: 1.4.0
api-version: 1.14
author: Weissfeuer
website: https://github.com/Weissfeuer/DistanceLeveledMonsters
description: Scales monster health / attack based on distance from spawn
main: io.github.weissfeuer.distanceleveledmonsters.DistanceLeveledMonsters
commands:
   DistanceLevel:
      description: Displays the monster level scaling at your current position.
      usage: /DistanceLevel [X-Coord] [Z-Coord]